version: '3'
services:
  maven:
    build:
     context: .
     dockerfile: Dockerfile_maven
    volumes:
     - mvn_volume:/box/app
  tomcat:
    build:
      context: .
      dockerfile: Dockerfile_tomcat
    ports:
      - "8080:8080"
    volumes:
      - app_volume:/usr/local/tomcat/webapps
volumes:
  app_volume:
  mvn_volume:
  