FROM maven:3.6.3-jdk-11
WORKDIR ./box
#копирование файлов проекта внутрь образа
COPY ./boxfuse ./
#сборка
RUN mvn package
#создание отдельной папки с готовым артефактом
RUN jar xvf ./target/hello-1.0.war
RUN mkdir ./app
RUN cp -r ./target/hello-1.0/ ./app/hello/