version: '3'
services:
  maven:
    build:
     context: .
     dockerfile: Dockerfile_maven
    volumes:
     - volume1:/box/app
  tomcat:
    build:
      context: .
      dockerfile: Dockerfile_tomcat
    ports:
      - "8080:8080"
    volumes:
      - volume1:/usr/local/tomcat/webapps
volumes:
  volume1:
