---
# tasks file for prod
- name: Install Tomcat 9
  apt:
    name: tomcat9 
    state: present

- name: Ensure Tomcat9 is started and enabled on boot.
  service:
    name: tomcat9
    state: started 
    enabled: yes

- name: Copy Remote-To-Remote (from serverA to serverB)
  synchronize: src="{{app_dir_on_build}}" dest="{{tomcat_dir}}"/webapps/
  delegate_to: build
  notify: restart_tomcat