FROM maven:3.6.3-jdk-11 as builder
RUN apt install git -y
RUN mkdir /apps
WORKDIR /apps
RUN git clone https://github.com/boxfuse/boxfuse-sample-java-war-hello.git ./boxfuse
RUN mvn -f /apps/boxfuse/pom.xml package -DskipTests

FROM tomcat:9-alpine
COPY --from=builder /apps/boxfuse/target/hello-1.0.war /usr/local/tomcat/webapps/hello.war
CMD ["catalina.sh", "run"]