- name: install common apts
  hosts: localhost, prod

  tasks:
  - name: ensure docker package is present
    apt:
     name: docker.io
     state: present

  - name: ensure python-pip package is present
    apt:
     name: python-pip
     state: present

  - name: ensure python-apt is present
    apt:
     name: python-apt
     state: present
  
  - name: ensure python module for docker is present
    pip:
     name: docker
     state: present

- name: build docker image
  hosts: local
  vars_prompt:
  - name: username
    prompt: Enter Docker username
  - name: email
    prompt: Enter Docker email
  - name: password
    prompt: Enter Docker password

  tasks:
  - name: log into DockerHub
    docker_login:
     username: "{{ username }}"
     email: "{{ email }}"
     password: "{{ password }}"

  - name: build and push image to registry
    docker_image:
     build:
      path: .
     name: ansible-docker
     repository: corneliusdrebbel/repo1:ansible-docker
     source: build
     force_tag: yes
     state: present
     push: yes

- name: prod server provisioning
  hosts: prod
  become: yes

  - name: pull image from registry and start container
    docker_container:
     name: ansible-docker
     image: corneliusdrebbel/repo1:ansible-docker
     pull: yes
     state: started
     restart: yes
     ports:
      - "0.0.0.0:8080:8080"