version: '3.3'
services: 
    web:
        build: .
        ports:
         - "8080:8080"
    db:
        image: mysql
        environment:
         MYSQL_ROOT_PASSWORD: my-secret-1
         MYSQL_USER: "db_user_1"
         MYSQL_PASSWORD: "my_super_secret_1"
         MYSQL_DATABASE: "database1"
         
        ports:
         - "3306:3306"
         - "33060:33060"
