- name: Create a sandbox instance
  hosts: localhost
  gather_facts: False
  vars:
    keypair: devops
    instance_type: t2.micro
    security_group: mysecgp1
    image: ami-0e1ce3e0deb8896d2
    region: eu-central-1
  tasks:
    - name: Launch instance
      amazon.aws.ec2:
         profile: default
         key_name: "{{ keypair }}"
         group: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
         vpc_subnet_id: subnet-11f26b7b
         assign_public_ip: yes
         count: 2
      register: ec2

     - name: adding host to master
        add_host:
         name: "{{ ec2.instances[0]['public_ip'] }}"
         groups: build-group

     - name: adding host to master
        add_host:
         name: "{{ ec2.instances[1]['public_ip'] }}"
         groups: prod-group

#    - name: Add new instance to host group
#      add_host:
#        hostname: "{{ item.public_ip }}"
#        groupname: launched
#      loop: "{{ ec2.instances }}"

#    - name: Wait for SSH to come up
#      delegate_to: "{{ item.public_dns_name }}"
#      wait_for_connection:
#        delay: 60
#        timeout: 320
#      loop: "{{ ec2.instances }}"

- name: Configure build server
  hosts: build-group
  become: True
  roles:
    - common
    - build

- name: Configure prod server
  hosts: prod-group
  become: True
  roles:
    - common
    - prod
