---
- name: Create instances
  hosts: localhost
  gather_facts: False
  connection: local
  vars:
    keypair: devops
    instance_type: t2.micro
    security_group: mysecgp1
    image: ami-0e1ce3e0deb8896d2
    region: eu-central-1
  tasks:
    - name: Launch instance
      ec2:
         profile: default
         key_name: "{{ keypair }}"
         group: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
         vpc_subnet_id: subnet-11f26b7b
         assign_public_ip: yes
         count: 2
      register: ec2

    - name: adding host to build-group
      add_host:
         name: "{{ ec2.instances[0]['public_ip'] }}"
         groups: build-group

    - name: adding host to prod-group
      add_host:
         name: "{{ ec2.instances[1]['public_ip'] }}"
         groups: prod-group

    - name: Wait for SSH to come up
      delegate_to: "{{ item.public_ip }}"
      wait_for_connection:
        delay: 60
        timeout: 320
      loop: "{{ ec2.instances }}"   

- name: Provisioning
  hosts: build-group, prod-group
  tasks:
    - name: Configure build server
      hosts: build-group
      become: yes
      roles:
       - common
       - build

    - name: Configure prod server
      hosts: prod-group
      become: yes
      roles:
       - common
       - prod