---
- name: Create instances
  hosts: localhost
  gather_facts: False
  vars:
    instance_type: t2.micro
    security_group: mysecgp1
    image: ami-0e1ce3e0deb8896d2
    region: eu-central-1

  tasks:

    - name: create key pair
      ec2_key:
        name: devops13
        region: eu-central-1
        force: yes
      register: ec2_key_result

    - name: Save private key
      copy: content="{{ ec2_key_result.key.private_key }}" dest="~/.ssh/id_rsa" mode=0600

    - name: Launch instance
      ec2:
         profile: default
         key_name: devops13
         group: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
         vpc_subnet_id: subnet-11f26b7b
         assign_public_ip: yes
         count: 2
      register: ec2

    - name: adding host to buildgroup
      add_host:
         name: "{{ ec2.instances[0].public_ip }}"
         groups: buildgroup

    - name: adding host to prodgroup
      add_host:
         name: "{{ ec2.instances[1].public_ip }}"
         groups: prodgroup

    - name: Wait for SSH to come up
      wait_for:
         host: "{{ item.public_ip }}"
         port: 22
         state: started
      with_items: "{{ec2.instances}}" 

    - name: Pause 15 sec
      pause:
         seconds: 15

- name: Provisioning build
  hosts: buildgroup
  become: yes
  remote_user: ubuntu
  roles:
   - common
   - build

- name: Provisioning prod
  hosts: prodgroup
  become: yes
  remote_user: ubuntu
  roles:
   - common
   - prod